import "@mantine/core/styles.css";
import "@mantine/charts/styles.css";
import "@mantine/notifications/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/nprogress/styles.css";

import React from "react";

import {ColorSchemeScript, createTheme, MantineProvider} from "@mantine/core";

import {TRPCReactProvider} from "~/trpc/react";

import type {Metadata} from "next";


export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const theme = createTheme({});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ja">
    <head>
      <link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png"/>
      <link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png"/>
      <link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png"/>
      <link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#0ca678"/>
      <meta name="msapplication-TileColor" content="#ffffff"/>
      <meta name="theme-color" content="#ffffff"/>
      <ColorSchemeScript defaultColorScheme="auto"/>
    </head>
    <body>
    <TRPCReactProvider>
      <MantineProvider theme={theme} defaultColorScheme="auto">
        {children}
      </MantineProvider>
    </TRPCReactProvider>
    </body>
    </html>
  );
}
